version: "3.7"

services:
    slapi:
        image: $API_IMAGE
        ports:
            - "9002:3000"
            - target: 1444
              published: 1444
              protocol: udp
              mode: host
        restart: always
        environment:
            - SL_IP_ADDRESS
            - SL_PORT
        
    sl-frontend:
        image: $UI_IMAGE
        restart: always
        environment:
            API_BASE_URL: http://$SERVER_ADDRESS:9002/api
        ports:
            - "9001:80"
        